name: cloud_logger
description: cloud logger package
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.3.0
  universal_io: ^2.2.1
  stack_trace: ^1.11.0
  crypto: ^3.0.3
  device_info_plus: ^9.0.1
  universal_platform: ^1.0.0+1
  package_info_plus: ^4.0.1
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  uuid: ^3.0.7
  path_provider: ^2.0.15
  path: ^1.8.3
  singleton: ^0.0.3-nullsafety
  android_id: ^0.3.3

  robust_http:
    git:
      url: https://github.com/bookbot-kids/robust-http.git

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides: 
  collection: ^1.17.2

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
